# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy develop build"
  lane :develop do
      build_app(
        scheme: "Demo[STG]",
        export_method: "ad-hoc",
        export_options: {
          provisioningProfiles: {
            "com.kernelequity.topacts" => "TopActs[STG] - Firebase",
          }
        }
      )
  end
end
