# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#ENV['GOOGLE_APPLICATION_CREDENTIALS']='/Users/vijaychaudhary/Downloads/topacts-c5a63-firebase-adminsdk-ma6o0-584fc946e7.json',

default_platform(:ios)

platform :ios do
  desc "Deploy develop build"
  lane :develop do
      build_app(
        scheme: "Demo[STG]",
        export_method: "ad-hoc",
        export_options: {
          provisioningProfiles: {
            "com.kernelequity.topacts" => "TopActs[STG] - Firebase",
          }
        }
      )
      firebase_app_distribution(
        app: "1:1090731515040:ios:d483616e0d5f32b640bdc5",
        service_credentials_file:"firebase_credentials.json",
        testers: "vijay.chaudhary@kernelequity.com",
        release_notes: "Resolve the issue",
      )
  end

  lane :get_firebase_cli_token do
    ENV['GOOGLE_APPLICATION_CREDENTIALS']='/Users/vijaychaudhary/Downloads/topacts-c5a63-firebase-adminsdk-ma6o0-584fc946e7.json'
    
    firebase_cli_token = sh("firebase login:ci --no-localhost", log: true).strip
    # UI.success("Firebase CLI Token: #{firebase_cli_token}")
    # Use firebase_cli_token as needed in subsequent Fastlane actions or scripts
    if firebase_cli_token.empty?
      UI.error("Failed to get Firebase CLI token")
    else
      UI.success("Firebase CLI Token: #{firebase_cli_token}")
    end
  end

end
